### ISSUE TITLE
Work on several maps

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Node-Magnet#1]
Hi @EdoFro 

Thank you for "freeplane Node-Magnet" which is a tool that I find practical and well thought out. I see a typical use case that could be very interesting. 

I always have project maps that are open (usually 3 or 4) plus a dedicated task map thanks to the FreeplaneGTD+ addon. What would be very useful would be if I could create tasks (so nodes) in the projects and then "magnetize" them to the "inbox" node of my GTD card. 

What do you think about this idea? I don't realize if it would be possible/complicated?

**Comment by bepolymathe** [comment]
In the same time, i’am searching a way to create a new task in freeplane when i’am out of freeplane or when freeplane is closed. For me it’s relative to the first question. 

I made some quick test... i can launch a quick command with a shortcut that execute the following command where `ID_729892401` is the identity of my inbox node for task.

`sh /freeplane-1.8.8/freeplane.sh -XNewChildAction -XEditLongAction /home/manu/maps/todo.mm#ID_729892401`

Obviously it's a bit slow because you have to launch freeplane each time but it works for the moment...

**Comment by EdoFro** [comment]
Hi @bepolymathe ,
I've been making some tests with copying nodes from other maps to the active one. It's not so hard. I'm going to do something like the idea you are proposing, but not in the near future. 
I need something like that myself.

about the other idea:
maybe it is easier to write your tasks in a notepad app and import the file when you open freeplane. don't know

bye,
Edo

**Comment by bepolymathe** [comment]
Great. Thanks for reply. ;-)
